-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  name text,
  age integer,
  height numeric, -- in cm
  current_weight numeric, -- in kg
  goal text,
  
  -- Gamification Stats
  level integer default 1,
  xp integer default 0,
  max_xp integer default 100,
  rank text default 'E',
  str integer default 10,
  agi integer default 10,
  "end" integer default 10, -- "end" is a reserved keyword, quoted
  
  is_awakened boolean default false
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Weight History Table
create table weight_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    weight numeric not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table weight_logs enable row level security;

create policy "Users can view own weight logs."
  on weight_logs for select
  using ( auth.uid() = user_id );

create policy "Users can insert own weight logs."
  on weight_logs for insert
  with check ( auth.uid() = user_id );

-- Function to handle new user signup automatically (Trigger)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, is_awakened)
  values (new.id, new.raw_user_meta_data->>'name', false);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
