-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PROFILES TABLE
create table public.profiles (
  id uuid references auth.users not null primary key,
  name text,
  age integer,
  height float,
  current_weight float,
  goal text,
  
  -- Stats
  str integer default 10,
  agi integer default 10,
  endurance integer default 10,
  
  -- Progression
  level integer default 1,
  xp integer default 0,
  max_xp integer default 100,
  rank text default 'E',
  is_awakened boolean default false,
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;

-- Policies for Profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- WEIGHT LOGS TABLE
create table public.weight_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  weight float not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.weight_logs enable row level security;

-- Policies for Weight Logs
create policy "Users can view their own weight logs."
  on weight_logs for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own weight logs."
  on weight_logs for insert
  with check ( auth.uid() = user_id );

-- HANDLE NEW USER CREATION (Optional but recommended)
-- This ensures a profile row exists when a user signs up via Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, is_awakened)
  values (new.id, 'Hunter', false);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function on new user sign up
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
